### ISSUE TITLE
add ECS libraries to the benchmark

### ISSUE THREAD

**Issue by loudoweb** [eliasku/ecx-benchmarks#1]
Hello,

I love this idea to have benchmark on haxe ECS libraries.

Could you add [Seagal ](https://github.com/Tommislav/seagal/tree/seagal2)and [Eskimo](https://github.com/PDeveloper/eskimo)?

Thanks!

**Comment by eliasku** [comment]
Hi, 

Thank you for sharing. I hadn't found these libraries with google before!
1. I'm going to investigate and add `Seagal` as well.
2. Seems like `eskimo` is continuation of `hxE`, so I should just replace old by new one.

**Comment by loudoweb** [comment]
Thanks.
Please use **seagal2 branch** for `Seagal`. I heard from the author that it is more performant.

**Comment by eliasku** [comment]
@loudoweb `Eskimo` has been added. But I have a couple of issues: 
1. Java compilation is broken (haxelib) - https://github.com/PDeveloper/eskimo/issues/7
2. Performance for getting components with View is very slow, so for Eskimo I just decrease amount of iterations from 2000 to 100, (operations per second metrics was not affected off course). I just keep `hxE` test because it looks much faster. Maybe you know some specific way to get components fast on Eskimo (I didn't found any magic, seems like getting by Class ruins all performance)

**Comment by PDeveloper** [comment]
Ha! Nice stuff! (Thanks for these benchmarks)

Eskimo easy component access is currently very slow, being solved via macros to keep it concise, but have it performant. Perhaps I can write a more performant test? (The changes are minimal, and relate only to access components a different way. While verbose, this is similar to hxE)

And hxE is by design different than Eskimo. But these benchmarks are certainly food for thought.

**Comment by eliasku** [comment]
@PDeveloper Thanks! Could you share the snippet for Eskimo components fast-access pattern if any available?

**Comment by eliasku** [comment]
@loudoweb `Seagal` on the way, I will try to use current git-version, with branch... But it would be better to use just haxelib version (just because of defined version and cross-platform compilability)

**Comment by eliasku** [comment]
@loudoweb `Seagal` is not ready-to-bench library. `haxelib.json` is missed. Has dependencies to `dconsole` which haxelib version without patching in not 3.3 compatible. "ECS framework" is not separated from Game-Engine (already linked to flash API / nme / openfl). I able to compile it only for swf without nme/openfl. Seems like component access pattern is also classname-based and dramatically slow. But anyway, I did the tests, and boilerplate for `seagal` is prepared.

**Comment by loudoweb** [comment]
Ok thanks!

**Comment by PDeveloper** [comment]
Is there a way for the benchmark builder to use a specific branch for Eskimo?

Eskimo "next" branch is an optimized version with a few API changes as well. If you can switch to using that, I can update the benchmark. It's now somewhat competitive, but not close to ecx yet.

**Comment by eliasku** [comment]
@PDeveloper install your `next` branch to haxelib directly. Then in `ecx-benchmarks` folder run for example: `hxmake run -app=eskimo -target=swf,cpp` just modify arguments to check other platforms.
